---
- name: Copy some files into second windows
  hosts: dev
  tasks:
    - name: Copy a directory into the remote host
      ansible.windows.win_copy:
        src: C:\Users\Administrator\Documents\Testfolder
        dest: C:\Users\Administrator\Documents\Testfolder
        remote_src: true
      delegate_to: database
  
