---
- name: Instalando winscp via powershell con winget
  hosts: all
  tasks:
    - name: Instalando wincsp
      ansible.windows.win_powershell: 
        script: >
          winget install --id WinSCP.WinSCP
          --accept-source-agreements
        register: winscp_result

      changed_when: >
        "No available upgrade found" not in (winscp_result.output | join(' '))
         and
        "No newer package versions are available" not in (winscp_result.output | join(' '))
