---
- name: Instalando winscp via powershell con winget
  hosts: all
  tasks:
    - name: Instalando wincsp
      ansible.windows.win_shell: | 
        winget source reset --force
        winget source update
      changed_when: false

    - name: Instalando wincsp
      ansible.windows.win_shell: >
        winget install --id WinSCP.WinSCP
        --silent
        --source winget
        --accept-package-agreements
        --accept-source-agreements
      changed_when: false
