---
- name: Instalando winscp via powershell con winget
  hosts: winserver02
  vars_files:
    vault_windows.yml
  tasks:
    - name: Instalando wincsp
      ansible.windows.win_powershell: 
        script: >
          winget install --id WinSCP.WinSCP
          --accept-source-agreements
          --scope machine
      register: winscp_result
      changed_when: >
        'No available upgrade found.' not in winscp_result.output
        and
        'Found an existing package already installed.' not in winscp_result.output

    - name: Usando Winscp para sincronizar archivos
      ansible.windows.win_powershell:
        script: |
          & "C:\Program Files (x86)\WinSCP\WinSCP.com" /command
          "open sftp://{{remote_user}}:{{remote_password}}@10.0.32.221/"
          "mkdir /home/ansible/testfolder"
          "synchronize remote C:\Users\ansible.IPEXLAB\Documents\Testlocalfolder\ /home/ansible/tesfolder"
          "exit"
          
