---
- name: Consultar estado del proceso DNF
  ansible.builtin.async_status:
    jid: "{{ dnf_job.ansible_job_id }}"
  register: dnf_status
  failed_when: false

- name: Leer nuevo output de DNF
  ansible.builtin.shell: |
    inicio=$(cat {{ dnf_offset }})

    if [ -f {{ dnf_log }} ]; then
      total=$(wc -l < {{ dnf_log }})

      if [ "$total" -ge "$inicio" ]; then
        tail -n +"$inicio" {{ dnf_log }}
        echo $((total + 1)) > {{ dnf_offset }}
      fi
    fi
  register: dnf_output
  changed_when: false
  failed_when: false

- name: Mostrar nuevo output
  ansible.builtin.debug:
    msg: "{{ dnf_output.stdout_lines }}"
  when:
    - dnf_output.stdout is defined
    - dnf_output.stdout | length > 0

- name: Fallar si DNF termino con error
  ansible.builtin.fail:
    msg: |
      DNF terminó con error.
      Return code: {{ dnf_status.rc }}
  when:
    - dnf_status.finished | default(false) | bool
    - dnf_status.rc is defined
    - dnf_status.rc | int != 0

- name: Finalizar monitoreo si DNF termino correctamente
  ansible.builtin.meta: end_host
  when:
    - dnf_status.finished | default(false) | bool
    - dnf_status.rc is defined
    - dnf_status.rc | int == 0

- name: Esperar antes de la proxima lectura
  ansible.builtin.pause:
    seconds: 1
  when:
    - not (dnf_status.finished | default(false) | bool)
